export const trending = {
  page: 1,
  results: [
    {
      id: 499932,
      video: false,
      vote_count: 207,
      vote_average: 7.6,
      title: 'The Devil All the Time',
      release_date: '2020-09-11',
      original_language: 'en',
      original_title: 'The Devil All the Time',
      genre_ids: [80, 18, 53],
      backdrop_path: '/rUeqBuNDR9zN6vZV9kpEFMtQm0E.jpg',
      adult: false,
      overview:
        'In Knockemstiff, Ohio and its neighboring backwoods, sinister characters converge around young Arvin Russell as he fights the evil forces that threaten him and his family.',
      poster_path: '/hqTavMAi69tdWuuFjfcIzs1y2cf.jpg',
      popularity: 109.858,
      media_type: 'movie',
    },
    {
      backdrop_path: '/zx3m4iW6CsM7yuMEUyvSkvbwaip.jpg',
      first_air_date: '2020-09-18',
      genre_ids: [18, 80, 9648],
      id: 81354,
      name: 'Ratched',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Ratched',
      overview:
        "An origins story, beginning in 1947, which follows Ratched's journey and evolution from nurse to full-fledged monster tracking her murderous progression through the mental health care system.",
      poster_path: '/cDNxOIm6K5D2W21QyJWZ95sJzQt.jpg',
      vote_average: 7.9,
      vote_count: 15,
      popularity: 63.757,
      media_type: 'tv',
    },
    {
      id: 337401,
      video: false,
      vote_count: 1707,
      vote_average: 7.5,
      title: 'Mulan',
      release_date: '2020-09-10',
      original_language: 'en',
      original_title: 'Mulan',
      genre_ids: [28, 12, 18, 14, 10752],
      backdrop_path: '/zzWGRw277MNoCs3zhyG3YmYQsXv.jpg',
      adult: false,
      overview:
        'When the Emperor of China issues a decree that one man per family must serve in the Imperial Chinese Army to defend the country from Huns, Hua Mulan, the eldest daughter of an honored warrior, steps in to take the place of her ailing father. She is spirited, determined and quick on her feet. Disguised as a man by the name of Hua Jun, she is tested every step of the way and must harness her innermost strength and embrace her true potential.',
      poster_path: '/aKx1ARwG55zZ0GpRvU2WrGrCG9o.jpg',
      popularity: 1457.551,
      media_type: 'movie',
    },
    {
      backdrop_path: '/ogAoaYiqwkV7Qm2JFvUKMSihmIL.jpg',
      first_air_date: '2020-09-18',
      genre_ids: [10759, 16],
      id: 93741,
      name: 'Jurassic World: Camp Cretaceous',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Jurassic World: Camp Cretaceous',
      overview:
        'Six teens attending an adventure camp on the opposite side of Isla Nublar must band together to survive when dinosaurs wreak havoc on the island.',
      poster_path: '/jWTDtbp2TnUGw1OJoDqq2O9IS0M.jpg',
      vote_average: 8.9,
      vote_count: 8,
      popularity: 52.059,
      media_type: 'tv',
    },
    {
      id: 627290,
      video: false,
      vote_count: 35,
      vote_average: 5.9,
      title: 'Antebellum',
      release_date: '2020-09-02',
      original_language: 'en',
      original_title: 'Antebellum',
      genre_ids: [27],
      backdrop_path: '/5Pa914tmQH0OXZvENKUi9HxZkNY.jpg',
      adult: false,
      overview:
        "Successful author Veronica finds herself trapped in a horrifying reality and must uncover the mind-bending mystery before it's too late.",
      poster_path: '/wRPxVAIRS0i3O6yYuKcVsuvl5vQ.jpg',
      popularity: 32.103,
      media_type: 'movie',
    },
    {
      original_name: 'Raised by Wolves',
      id: 85723,
      name: 'Raised by Wolves',
      vote_count: 197,
      vote_average: 7.5,
      first_air_date: '2020-09-03',
      poster_path: '/mTvSVKMn2Npf6zvYNbGMJnYLtvp.jpg',
      genre_ids: [18, 10765],
      original_language: 'en',
      backdrop_path: '/na2xUduK8HviOFT97TiFG2MkJmY.jpg',
      overview:
        'After Earth is ravaged by a great religious war, an atheistic android architect sends two of his creations, Mother and Father, to start a peaceful, godless colony on the planet Kepler-22b. Their treacherous task is jeopardized by the arrival of the Mithraic, a deeply devout religious order of surviving humans.',
      origin_country: ['US'],
      popularity: 613.401,
      media_type: 'tv',
    },
    {
      id: 701175,
      video: false,
      vote_count: 50,
      vote_average: 6.1,
      title: 'The Paramedic',
      release_date: '2020-09-16',
      original_language: 'es',
      original_title: 'El practicante',
      genre_ids: [18, 53],
      backdrop_path: '/lOQGb1IqtBw6l7BR6ODBikYbQhZ.jpg',
      adult: false,
      overview:
        'Unable to face his new reality in a wheelchair, Ángel develops a deadly obsession with the woman who left him and unleashes a sinister revenge plot.',
      poster_path: '/l9ruFmHoUws4A45s8FBZuMNC6Mu.jpg',
      popularity: 82.271,
      media_type: 'movie',
    },
    {
      original_name: 'The Boys',
      id: 76479,
      name: 'The Boys',
      vote_count: 1962,
      vote_average: 8.4,
      first_air_date: '2019-07-25',
      poster_path: '/mY7SeH4HFFxW1hiI6cWuwCRKptN.jpg',
      genre_ids: [10759, 10765],
      original_language: 'en',
      backdrop_path: '/mGVrXeIjyecj6TKmwPVpHlscEmw.jpg',
      overview:
        'A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.',
      origin_country: ['US'],
      popularity: 2130.788,
      media_type: 'tv',
    },
    {
      adult: false,
      backdrop_path: '/mwXmcrvjOJwzsJSuNEupjisXUt6.jpg',
      genre_ids: [18, 53],
      id: 479259,
      original_language: 'en',
      original_title: 'Lost Girls and Love Hotels',
      overview:
        'Margaret finds herself in the glittering labyrinth of Tokyo by night and as a respected english teacher of a Japanese flight attendant academy by day. With little life direction, Margaret searches for meaning with fellow ex-pats in a Japanese dive bar, drinking to remember to forget and losing herself in love hotel encounters with men who satisfy a fleeting craving. When Margaret crosses paths with a dashing Yakuza, Kazu, she falls in love with him despite the danger and tradition that hinders their chances of being together. We follow Margaret through the dark and light of love and what it means to find oneself abroad with a youthful abandon.',
      poster_path: '/ywxH6Z3LvEFyReqg0MYmcPPGzR2.jpg',
      release_date: '2020-09-18',
      title: 'Lost Girls and Love Hotels',
      video: false,
      vote_average: 5,
      vote_count: 2,
      popularity: 68.958,
      media_type: 'movie',
    },
    {
      original_name: 'ドラゴンズドグマ',
      id: 99769,
      name: 'Dragon’s Dogma',
      vote_count: 6,
      vote_average: 6.3,
      first_air_date: '2020-09-17',
      poster_path: '/m8VA5fudLl3jXywxxSsE4g5ltYS.jpg',
      genre_ids: [16, 10759, 10765],
      original_language: 'ja',
      backdrop_path: '/1RRNYOcDlQeMASFF622T4Bxfp2z.jpg',
      overview:
        'Ethan sets out to vanquish the Dragon that took his heart, but with every demon he battles, the more he loses his humanity.',
      origin_country: ['JP'],
      popularity: 63.195,
      media_type: 'tv',
    },
    {
      id: 726739,
      video: false,
      vote_count: 28,
      vote_average: 7.1,
      title: 'Cats & Dogs 3: Paws Unite',
      release_date: '2020-10-09',
      original_language: 'en',
      original_title: 'Cats & Dogs 3: Paws Unite',
      genre_ids: [28, 35],
      backdrop_path: '/axPvTxOKwbV70hdJgf3SfI71gDn.jpg',
      adult: false,
      overview:
        "It's been ten years since the creation of the Great Truce, an elaborate joint-species surveillance system designed and monitored by cats and dogs to keep the peace when conflicts arise. But when a tech-savvy villain hacks into wireless networks to use frequencies only heard by cats and dogs, he manipulates them into conflict and the worldwide battle between cats and dogs is BACK ON. Now, a team of inexperienced and untested agents will have to use their old-school animal instincts to restore order and peace between cats and dogs everywhere.",
      poster_path: '/4BgSWFMW2MJ0dT5metLzsRWO7IJ.jpg',
      popularity: 45.55,
      media_type: 'movie',
    },
    {
      id: 577922,
      video: false,
      vote_count: 1606,
      vote_average: 7.5,
      title: 'Tenet',
      release_date: '2020-08-22',
      original_language: 'en',
      original_title: 'Tenet',
      genre_ids: [28, 878, 53],
      backdrop_path: '/wzJRB4MKi3yK138bJyuL9nx47y6.jpg',
      adult: false,
      overview:
        'Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.',
      poster_path: '/k68nPLbIST6NP96JmTxmZijEvCA.jpg',
      popularity: 292.445,
      media_type: 'movie',
    },
    {
      id: 606625,
      video: false,
      vote_count: 18,
      vote_average: 6.2,
      title: 'Follow Me',
      release_date: '2020-07-16',
      original_language: 'en',
      original_title: 'Follow Me',
      genre_ids: [12, 27, 53],
      backdrop_path: '/uz22R8kBpIaUC8pkOKZm7jZfLGN.jpg',
      adult: false,
      overview:
        'A social media personality travels with his friends to Moscow to capture new content for his successful VLOG. Always pushing the limits and catering to a growing audience, they enter a cold world of mystery, excess, and danger. When the lines between real life and social media are blurred, the group must fight to escape, and survive.',
      poster_path: '/glwOyoD0Pzxzyb3l7nELEgjSjQ8.jpg',
      popularity: 21.694,
      media_type: 'movie',
    },
    {
      original_name: 'The Third Day',
      id: 90259,
      name: 'The Third Day',
      vote_count: 5,
      vote_average: 7.2,
      first_air_date: '2020-09-14',
      poster_path: '/rNx7hgp3Cs6YPeBgvE6enNmR1Xz.jpg',
      genre_ids: [18, 9648, 10765],
      original_language: 'en',
      backdrop_path: '/yEvcaFO2nz8QdGVsqyVK93iLPp3.jpg',
      overview:
        'A unique story told over two distinct halves, "Summer" follows Sam, a man drawn to a mysterious island off the British coast where he encounters a group of islanders set on preserving their traditions at any cost. "Winter" follows Helen, a strong-willed outsider who comes to the island seeking answers, but whose arrival precipitates a fractious battle to decide its fate.',
      origin_country: ['US'],
      popularity: 191.51,
      media_type: 'tv',
    },
    {
      original_name: 'The 100',
      id: 48866,
      name: 'The 100',
      vote_count: 4303,
      vote_average: 7.7,
      first_air_date: '2014-03-19',
      poster_path: '/wcaDIAG1QdXQLRaj4vC1EFdBT2.jpg',
      genre_ids: [18, 10759, 10765],
      original_language: 'en',
      backdrop_path: '/hTExot1sfn7dHZjGrk0Aiwpntxt.jpg',
      overview:
        "100 years in the future, when the Earth has been abandoned due to radioactivity, the last surviving humans live on an ark orbiting the planet — but the ark won't last forever. So the repressive regime picks 100 expendable juvenile delinquents to send down to Earth to see if the planet is still habitable.",
      origin_country: ['US'],
      popularity: 569.639,
      media_type: 'tv',
    },
    {
      original_name: 'Das letzte Wort',
      id: 110152,
      name: 'The Last Word',
      vote_count: 1,
      vote_average: 6,
      first_air_date: '2020-09-17',
      poster_path: '/agF87jI4RaovHtt2upMreJ81UuM.jpg',
      genre_ids: [35, 18],
      original_language: 'de',
      backdrop_path: '/l093GzwXBG87x3eq5JCuelwaPSU.jpg',
      overview:
        "A story about a funeral eulogy speaker who loses faith in her work and tries to sabotage her husband's funeral.",
      origin_country: ['DE'],
      popularity: 1.96,
      media_type: 'tv',
    },
    {
      id: 638134,
      video: false,
      vote_count: 35,
      vote_average: 6.4,
      title: 'Pets United',
      release_date: '2019-11-08',
      original_language: 'en',
      original_title: 'Pets United',
      genre_ids: [12, 16, 35, 10751],
      backdrop_path: '/ePkagE11fpUbTasJ2udxTJHuaWU.jpg',
      adult: false,
      overview:
        'When Roger (a Robin Hood-esque, stray dog) and Belle (an elegant yet spoilt pet cat) are thrown together amidst the chaos of a robot take-over of their home city, they must push all their preconceptions aside in order to survive, as they embark on a high-stakes, action-packed adventure.',
      poster_path: '/gtwqIYSOCRwEndZTg9s6iWjEZc1.jpg',
      popularity: 86.397,
      media_type: 'movie',
    },
    {
      backdrop_path: '/xq7Ptqf7GX9BAXamONFzOPOR6Op.jpg',
      first_air_date: '2020-09-16',
      genre_ids: [99],
      id: 108298,
      name: 'Challenger: The Final Flight',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Challenger: The Final Flight',
      overview:
        "Engineers, officials and the crew members' families provide their perspective on the 1986 Space Shuttle Challenger disaster and its aftermath.",
      poster_path: '/nJqCgP3vzu79mtf3i51Dv2B20Oy.jpg',
      vote_average: 10,
      vote_count: 1,
      popularity: 55.2,
      media_type: 'tv',
    },
    {
      id: 623491,
      video: false,
      vote_count: 282,
      vote_average: 6.7,
      title: 'The Babysitter: Killer Queen',
      release_date: '2020-09-10',
      original_language: 'en',
      original_title: 'The Babysitter: Killer Queen',
      genre_ids: [35, 27],
      backdrop_path: '/naUJGskMlDg2HZ0FhsaMG5xPF2K.jpg',
      adult: false,
      overview:
        "Two years after defeating a satanic cult led by his babysitter Bee, Cole's trying to forget his past and focus on surviving high school. But when old enemies unexpectedly return, Cole will once again have to outsmart the forces of evil.",
      poster_path: '/imy1OoT1xddt2kqw6hhc4v01e8i.jpg',
      popularity: 295.364,
      media_type: 'movie',
    },
    {
      id: 656690,
      video: false,
      vote_count: 138,
      vote_average: 8.2,
      title: 'The Social Dilemma',
      release_date: '2020-01-26',
      original_language: 'en',
      original_title: 'The Social Dilemma',
      genre_ids: [99, 18],
      backdrop_path: '/i26FIo5vJrR4u8ZZBm8o5Q4T9di.jpg',
      adult: false,
      overview:
        'This documentary-drama hybrid explores the dangerous human impact of social networking, with tech experts sounding the alarm on their own creations.',
      poster_path: '/VAXS2hbKwCKd3DEz57Cr6ch61s.jpg',
      popularity: 86.605,
      media_type: 'movie',
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};
